.local/share/hunspell:
  type: archive
  url: https://github.com/shuLhan/hunspell-id/archive/refs/heads/master.zip
  exact: false
  stripComponents: 1
  refreshPeriod: 168h
  include:
    - "*/id_ID.*"
.config/inkscape/extensions/inkscapeMadeEasy:
  type: archive
  url: https://github.com/fsmMLK/inkscapeMadeEasy/archive/refs/heads/master.zip
  exact: true
  stripComponents: 2
  refreshPeriod: 168h
  include:
    - "*/latest/**"
.config/inkscape/extensions/inkscapeCartesianPlotFunction2D:
  type: archive
  url: https://github.com/fsmMLK/inkscapeCartesianPlotFunction2D/archive/refs/heads/master.zip
  exact: true
  stripComponents: 2
  refreshPeriod: 168h
  include:
    - "*/latest/**"
.config/inkscape/extensions/inkscapeDimensions:
  type: archive
  url: https://github.com/fsmMLK/inkscapeDimensions/archive/refs/heads/master.zip
  exact: true
  stripComponents: 2
  refreshPeriod: 168h
  include:
    - "*/latest/**"
.config/inkscape/extensions/inkscapeCircuitSymbols:
  type: archive
  url: https://github.com/fsmMLK/inkscapeCircuitSymbols/archive/refs/heads/master.zip
  exact: true
  stripComponents: 2
  refreshPeriod: 168h
  include:
    - "*/latest/**"
