.local/share/hunspell:
  type: archive
  url: https://github.com/shuLhan/hunspell-id/archive/refs/heads/master.zip
  exact: false
  stripComponents: 1
  refreshPeriod: 168h
  include:
    - "*/id_ID.*"
